<template>
  <div class="relative">
     <!-- Options Button -->
    <PlotWOptions v-if="checkData.value" class="copy-icon" :items="dialogItems" :currentCollection="current_collection" />
    
    <!-- Header -->
    <div class="mt-4 mb-0">
        <h6 class="text-center text-2xl font-semibold">Data formats</h6>

        <div class="flex flex-wrap lg:flex-nowrap lg:h-full mt-4"> <!-- Left Column: Description -->

           <!-- Right Column: Stats Card -->
          <div class="flex-1 lg:w-4/5  flex flex-col justify-left lg:h-full ml-8 p-2">
              <p style="line-height: 1.8" class="card-content-vs  text-sm text-gray-700">
                The file formats supported or generated by a software tool define how it exchanges data with other tools and systems.
                Understanding format support is essential for assessing software <span class="highlight">Interoperability</span> and <span class="highlight">Reusability</span>—two key principles of FAIR.
              </p>
              <p style="line-height: 1.8" class="card-content-vs  text-sm text-gray-700 mt-2">
                Formats also offer insight into domain conventions, data standards, and the potential for integration into Open Science workflows across the Life Sciences.

              </p>
          </div>

          <div class="lg:w-1/5 flex items-center lg:h-full mr-8 p-2"> <!-- Loader -->
            <USkeleton v-if="isFormatsCountLoading" class="h-full w-full" />
              <!-- Card with Percentage -->
              <div v-else
                  class="text-center bg-indigo-50 rounded flex flex-col justify-center items-center p-3.5">
                  <p class="text-4xl mb-1">{{ percentage.toFixed(1) }}%</p>
                  <p class="font-light mb-0">
                      of software use standard<span class="font-bold">data formats</span>
                  </p>
              </div>
          </div>
        </div>
    </div>

    <div class="d-flex justify-content-around">
        <div v-if="isInputFormatsLoaing">
          <USkeleton class="h-52 mb-3 mx-10" />
        </div>
        <div v-else class="w-full md:w-[45%] gap-8">
          <FormatsPlot  v-if="checkData.value" :data="inputFormatsData" color="#F7B55E" />
          <p class="mt-2 text-center mb-2 ml-8">
            <span class="text-sm highlight" v-if="current_collection==='tools'">
            Input formats most frequently supported by tools in the Life Sciences, showing common standards.
            </span>
            <span class="text-sm highlight" v-else>
            Input formats most frequently supported by tools in {{ current_collection }}, showing common standards.
            </span>
          </p>
        </div>

        <div v-if="isOutputFormatsLoaing">
          <USkeleton class="h-52 mb-3 mx-10" />
        </div>
        <div v-else class="w-full md:w-[45%] gap-8">
        <FormatsPlot v-if="checkData.value" :data="outputFormatsData" color="#6FAD6F" />
        <p class="mt-2 text-center mb-2 ml-8">
            <span class="text-sm highlight" v-if="current_collection==='tools'">
            Output formats most frequently supported by tools in the Life Sciences, showing common standards.
            </span>
            <span class="text-sm highlight" v-else>
            Output formats most frequently supported by tools in {{ current_collection }}, showing common standards.
            </span>
          </p>
        </div>
      </div>
  </div>
</template>

<script setup>
import { onMounted, computed } from 'vue'
import { useTrends } from '../../../../stores/observatory/trends.js'
import FormatsPlot from './FormatsPlot.vue'
import { useObservatory } from '@/stores/observatory/index.js';
import { embedCodes } from '~/components/Observatory/visualizations/embedCodes.js';
import PlotWOptions from '~/components/Observatory/PlotWOptions.vue';


const trends = useTrends()
const observatoryStore = useObservatory();

const dialogItems = [embedCodes.dependencies]; // Define in `embedCodes.js`
const current_collection = computed(() => observatoryStore.currentCollection);


const inputFormatsData = computed(() => trends.InputFormats.data)
const outputFormatsData = computed(() => trends.OutputFormats.data)
const percentage = computed(() => trends.FormatsCount.data.percentage*100)

const isInputFormatsLoaing = computed(() => trends.unLoaded.inputFormats)
const isOutputFormatsLoaing = computed(() => trends.unLoaded.outputFormats)
const isFormatsCountLoading = computed(() => trends.unLoaded.formatsCount)


const checkData = ref(false);


onMounted(async () => {
  await trends.getInputFormats();
  await trends.getOutputFormats();
  await trends.getFormatsCount();

  checkData.value = computed(() => inputFormatsData != {} )
})

</script>

<script>
export default {
  name: 'FormatsMain'
};
</script>

  <style scoped>
  .highlight {
    color: #001752f8;
    font-weight: 500;
  }
  .copy-icon {
    position: absolute;
    top: 5px;
    right: 10px;
  }
  .card-content-vs {
    font-size: 0.9em !important;
    width: 95%;
    margin: auto;
  }
  </style>