<template>
  <div class="relative">
     <!-- Options Button -->
    <PlotWOptions v-if="checkData.value" class="copy-icon" :items="dialogItems" :currentCollection="current_collection" />
    
    <!-- Header -->
    <div class="text-center mt-4 mb-0">
        <h6 class="text-2xl font-semibold">Data formats</h6>
        <p class="card-content-vs text-sm mt-4 text-gray-700" style="line-height: 1.8">
          The file formats supported or generated by a software tool define how it exchanges data with other tools and systems.
          Understanding format support is essential for assessing software <span class="highlight">Interoperability</span> and <span class="highlight">Reusability</span>—two key principles of FAIR.
          <br />
          Formats also offer insight into domain conventions, data standards, and the potential for integration into Open Science workflows across the Life Sciences.
        </p>
    </div>

    <div class="d-flex justify-content-around">
        <div v-if="isInputFormatsLoaing">
          <USkeleton class="h-52 mb-3 mx-10" />
        </div>
        <div v-else class="w-full md:w-[45%] gap-8">
          <FormatsPlot  v-if="checkData.value" :data="inputFormatsData" color="#F7B55E" />
          <p class="mt-2 text-center mb-2 ml-8">
            <span class="text-sm highlight" v-if="current_collection==='tools'">
            Input formats most frequently supported by tools in the Life Sciences, showing common standards.
            </span>
            <span class="text-sm highlight" v-else>
            Input formats most frequently supported by tools in {{ current_collection }}, showing common standards.
            </span>
          </p>
        </div>

        <div v-if="isOutputFormatsLoaing">
          <USkeleton class="h-52 mb-3 mx-10" />
        </div>
        <div v-else class="w-full md:w-[45%] gap-8">
        <FormatsPlot v-if="checkData.value" :data="outputFormatsData" color="#6FAD6F" />
        <p class="mt-2 text-center mb-2 ml-8">
            <span class="text-sm highlight" v-if="current_collection==='tools'">
            Output formats most frequently supported by tools in the Life Sciences, showing common standards.
            </span>
            <span class="text-sm highlight" v-else>
            Output formats most frequently supported by tools in {{ current_collection }}, showing common standards.
            </span>
          </p>
        </div>
      </div>
  </div>
</template>

<script setup>
import { onMounted, computed } from 'vue'
import { useTrends } from '../../../../stores/observatory/trends.js'
import FormatsPlot from './FormatsPlot.vue'
import { useObservatory } from '@/stores/observatory/index.js';
import { embedCodes } from '~/components/Observatory/visualizations/embedCodes.js';
import PlotWOptions from '~/components/Observatory/PlotWOptions.vue';


const trends = useTrends()
const observatoryStore = useObservatory();

const dialogItems = [embedCodes.dependencies]; // Define in `embedCodes.js`
const current_collection = computed(() => observatoryStore.currentCollection);


const inputFormatsData = computed(() => trends.InputFormats.data)
const outputFormatsData = computed(() => trends.OutputFormats.data)
const isInputFormatsLoaing = computed(() => trends.unLoaded.inputFormats)
const isOutputFormatsLoaing = computed(() => trends.unLoaded.outputFormats)

const checkData = ref(false);


onMounted(async () => {
  await trends.getInputFormats();
  await trends.getOutputFormats();

  checkData.value = computed(() => inputFormatsData != {} )
})

</script>

<script>
export default {
  name: 'FormatsMain'
};
</script>

  <style scoped>
  .highlight {
    color: #001752f8;
    font-weight: 500;
  }
  .copy-icon {
    position: absolute;
    top: 5px;
    right: 10px;
  }
  .card-content-vs {
    font-size: 0.9em !important;
    width: 95%;
    margin: auto;
  }
  </style>