<template>
  <div class="relative">
    <!-- Options Button -->
    <PlotWOptions
      v-if="checkData"
      class="copy-icon"
      :items="dialogItems"
      :currentCollection="current_collection"
    />

    <!-- Header -->
    <div class="mt-4">
      <h6 class="text-2xl font-semibold text-center">Data formats</h6>

      <div class="row mt-4">
        <!-- Description -->
        <div class="col-lg-9 col-12">
          <p style="line-height: 1.8" class="card-content-vs text-sm text-gray-700">
            The file formats supported or generated by a software tool define
            how it exchanges data with other tools and systems. Understanding
            format support is essential for assessing software
            <span class="highlight">Interoperability</span> and
            <span class="highlight">Reusability</span>—two key principles of
            FAIR.
          </p>

          <p style="line-height: 1.8" class="card-content-vs text-sm text-gray-700 mt-2">
            Formats also offer insight into domain conventions, data
            standards, and the potential for integration into Open Science
            workflows across the Life Sciences.
          </p>
        </div>

        <!-- Percentage -->
        <div class="col-lg-3 col-12 mt-lg-0">
          <USkeleton
            v-if="isFormatsCountLoading"
            class="h-40"
          />

          <div
            v-else
            class="formats-percentage-card text-center d-flex flex-column justify-content-center align-items-center h-100"
          >
            <span class="formats-percentage">
              {{ percentage.toFixed(1) }}%
            </span>

            <p class="mb-0 mt-2 text-sm">
              of software use standard
              <span class="fw-semibold">data formats</span>
            </p>
          </div>
        </div>
      </div>
    </div>

    <!-- Plots -->
    <div class="row mt-5 mb-5">
      <!-- Input formats -->
      <div class="col-lg-6 col-12 mb-4 mb-lg-0">
        <div v-if="isInputFormatsLoading">
          <USkeleton class="h-80 mb-3 mx-10" />
        </div>

        <div v-else>
          <FormatsPlot
            v-if="checkData"
            :data="inputFormatsPlotData"
            color="#F7B55E"
          />

          <noDataAvailable v-else />

          <p class="mt-2 text-center mb-2">
            <span class="text-sm highlight">
              Input formats most frequently supported by tools in
              <template v-if="current_collection === 'tools'">
                the Life Sciences
              </template>
              <template v-else>
                {{ current_collection }}
              </template>,
              showing common standards
            </span>
          </p>
        </div>
      </div>

      <!-- Output formats -->
      <div class="col-lg-6 col-12">
        <div v-if="isOutputFormatsLoading">
          <USkeleton class="h-80 mb-3 mx-10" />
        </div>

        <div v-else>
          <FormatsPlot
            v-if="checkData"
            :data="outputFormatsPlotData"
            color="#6FAD6F"
          />

          <noDataAvailable v-else />

          <p class="mt-2 text-center mb-2">
            <span class="text-sm highlight">
              Output formats most frequently supported by tools in
              <template v-if="current_collection === 'tools'">
                the Life Sciences
              </template>
              <template v-else>
                {{ current_collection }}
              </template>,
              showing common standards
            </span>
          </p>
        </div>
      </div>
    </div>

    <UAlert
      color="orange"
      variant="soft"
      icon="i-lucide-triangle-alert"
      description="Most upstream sources we aggregate do not provide formats fields. Missing values reflect source limitations, not developer practices or lack of standard data formats."
      class="mt-4"
    />
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted } from "vue";
import FormatsPlot from "./FormatsPlot.vue";
import PlotWOptions from "~/components/Observatory/PlotWOptions.vue";
import noDataAvailable from "@/layouts/noDataAvailableImg.vue";
import { useTrends } from '@/stores/observatory/trends';
import { useObservatory } from '@/stores/observatory/index.js';
import { embedCodes } from "~/components/Observatory/visualizations/embedCodes.js";

// Store
const trendsStore = useTrends();
const observatoryStore = useObservatory();

const dialogItems = [
  embedCodes.inputFormats,
  embedCodes.outputFormats,
];

// Current Collection
const current_collection = computed(() => observatoryStore.currentCollection);

// Get Data
const inputFormats = computed(() => trendsStore.InputFormats);
const outputFormats = computed(() => trendsStore.OutputFormats);
const formatsCount = computed(() => trendsStore.FormatsCount);

// Loading States
const isInputFormatsLoading = computed(
  () => trendsStore.Loaded.inputFormats
);
const isOutputFormatsLoading = computed(
  () => trendsStore.Loaded.outputFormats
);
const isFormatsCountLoading = computed(
  () => trendsStore.Loaded.formatsCount
);

const percentage = computed(() => {
  const pct = formatsCount.value?.data.percentage;

  return typeof pct === "number" ? pct * 100 : 0;
});

const inputFormatsPlotData = computed(() => {
  if (!inputFormats.value) return {};

  console.log(inputFormats.value)
  return inputFormats.value.data
    ? inputFormats.value.data
    : inputFormats.value;
});

const outputFormatsPlotData = computed(() => {
  if (!outputFormats.value) return {};

  console.log(outputFormats.value)

  return outputFormats.value.data
    ? outputFormats.value.data
    : outputFormats.value;
});

const checkData = computed(() => {
  const input = inputFormatsPlotData.value;
  const output = outputFormatsPlotData.value;

  const inputOk =
    input &&
    typeof input === "object" &&
    Object.keys(input).length > 0;

  const outputOk =
    output &&
    typeof output === "object" &&
    Object.keys(output).length > 0;

  return inputOk || outputOk;
});

onMounted(async () => {
  await trendsStore.getInputFormats();
  await trendsStore.getOutputFormats();
  await trendsStore.getFormatsCount();
});
</script>

<style scoped>
.highlight {
  color: #001752f8;
  font-weight: 500;
}

.copy-icon {
  position: absolute;
  top: 5px;
  right: 10px;
}

.card-content-vs {
  font-size: 0.9em !important;
  width: 95%;
  margin: auto;
}

.formats-percentage-card {
  border-radius: 8px;
  padding: 0.5rem;
  background: #e4e9f2;
  min-height: 130px;
}

.formats-percentage {
  font-size: 2.4rem;
  line-height: 1;
  font-weight: 600;
}

</style>